export const Images = {
	map_bukal_sur: require("../assets/map/bukal_sur.jpg"),
	map_malabanan_norte: require("../assets/map/malabanan_norte.jpg"),
	map_malabanan_sur: require("../assets/map/malabanan_sur.jpg"),
	map_mangilag_norte: require("../assets/map/mangilag_norte.jpg"),
	map_mangilag_sur: require("../assets/map/mangilag_sur.jpg"),
	map_masalukot_I: require("../assets/map/masalukot_I.jpg"),
	map_masalukot_II: require("../assets/map/masalukot_II.jpg"),
	map_mayabobo: require("../assets/map/mayabobo.jpg"),
	map_pahinga_norte: require("../assets/map/pahinga_norte.jpg"),
	map_san_andres: require("../assets/map/san_andres.jpg"),
	map_sta_catalina_norte: require("../assets/map/sta_catalina_norte.jpg"),
	ic_disease_gray_fill: require("../assets/icons/ic_disease_gray_fill.png"),
	ic_disease_green_outline: require("../assets/icons/ic_disease_green_outline.png"),
	ic_pest_gray_fill: require("../assets/icons/ic_pest_gray_fill.png"),
	ic_pest_green_outline: require("../assets/icons/ic_pest_green_outline.png"),
	ic_nutrients_gray_fill: require("../assets/icons/ic_nutrients_gray_fill.png"),
	ic_nutrients_green_outline: require("../assets/icons/ic_nutrients_green_outline.png"),
	ic_nitrogen_gray_fill: require("../assets/icons/ic_nitrogen_gray_fill.png"),
	ic_nitrogen_green_outline: require("../assets/icons/ic_nitrogen_green_outline.png"),
};
